'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class eDB_FRPJ
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=eDB_FRPJ")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Property tbl_AgCc_Valida() As DbSet(Of tbl_AgCc_Valida)
    Public Property tbl_Agencias() As DbSet(Of tbl_Agencias)
    Public Property tbl_Atendimento() As DbSet(Of tbl_Atendimento)
    Public Property tbl_Atendimento_Expurgo() As DbSet(Of tbl_Atendimento_Expurgo)
    Public Property tbl_Bancos() As DbSet(Of tbl_Bancos)
    Public Property tbl_Canc_Alcada() As DbSet(Of tbl_Canc_Alcada)
    Public Property tbl_Canc_Codigo() As DbSet(Of tbl_Canc_Codigo)
    Public Property tbl_Canc_Data() As DbSet(Of tbl_Canc_Data)
    Public Property tbl_Canc_Local() As DbSet(Of tbl_Canc_Local)
    Public Property tbl_Canc_Lote_ID() As DbSet(Of tbl_Canc_Lote_ID)
    Public Property tbl_Canc_Motivo() As DbSet(Of tbl_Canc_Motivo)
    Public Property tbl_Canc_Motivo2() As DbSet(Of tbl_Canc_Motivo2)
    Public Property tbl_Canc_Tipo() As DbSet(Of tbl_Canc_Tipo)
    Public Property tbl_Cargo() As DbSet(Of tbl_Cargo)
    Public Property tbl_ChEps_Situacoes_Robo() As DbSet(Of tbl_ChEps_Situacoes_Robo)
    Public Property tbl_Dash_Template() As DbSet(Of tbl_Dash_Template)
    Public Property tbl_Desfecho() As DbSet(Of tbl_Desfecho)
    Public Property tbl_Eps() As DbSet(Of tbl_Eps)
    Public Property tbl_Plano() As DbSet(Of tbl_Plano)
    Public Property tbl_Procedente() As DbSet(Of tbl_Procedente)
    Public Property tbl_Produto() As DbSet(Of tbl_Produto)
    Public Property tbl_Produto_Categoria() As DbSet(Of tbl_Produto_Categoria)
    Public Property tbl_Produto_Classe() As DbSet(Of tbl_Produto_Classe)
    Public Property tbl_Produto_Grupo() As DbSet(Of tbl_Produto_Grupo)
    Public Property tbl_Produto_Segmento() As DbSet(Of tbl_Produto_Segmento)
    Public Property tbl_PzCurto_Percentual_Calc() As DbSet(Of tbl_PzCurto_Percentual_Calc)
    Public Property tbl_Retencao_Meta() As DbSet(Of tbl_Retencao_Meta)
    Public Property tbl_Retencao_Meta_PJ() As DbSet(Of tbl_Retencao_Meta_PJ)
    Public Property tbl_Tipo_Retencao() As DbSet(Of tbl_Tipo_Retencao)
    Public Property tbl_Usuario() As DbSet(Of tbl_Usuario)
    Public Property tbl_Usuario_Perfil() As DbSet(Of tbl_Usuario_Perfil)
    Public Property tsys_Parametro() As DbSet(Of tsys_Parametro)

End Class
