'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tbl_Atendimento_Expurgo
    Public Property CodId_Atend_Pk As Long
    Public Property Origem As Nullable(Of Integer)
    Public Property LigacaoData As Nullable(Of Date)
    Public Property LigacaoMesref As Nullable(Of Integer)
    Public Property Cnpj As Nullable(Of Long)
    Public Property RazaoSocial As String
    Public Property Cpf As Nullable(Of Long)
    Public Property Nome As String
    Public Property DDD As String
    Public Property Fone As String
    Public Property Ramal As String
    Public Property NCorrentista As Boolean
    Public Property Banco As Nullable(Of Integer)
    Public Property Agencia As Nullable(Of Integer)
    Public Property ContaCorrente As Nullable(Of Integer)
    Public Property DG As Nullable(Of Integer)
    Public Property CodId_Segmento_Fk As Nullable(Of Integer)
    Public Property DataNasc As Nullable(Of Date)
    Public Property Idade As Nullable(Of Integer)
    Public Property CodProduto_Rector As Nullable(Of Integer)
    Public Property CodProduto_VC As Nullable(Of Integer)
    Public Property CodId_Prod_Grupo_Fk As Nullable(Of Integer)
    Public Property DataIniVig As Nullable(Of Date)
    Public Property DataFimVig As Nullable(Of Date)
    Public Property Proposta As Nullable(Of Long)
    Public Property Apolice As Nullable(Of Long)
    Public Property Certificado As Nullable(Of Long)
    Public Property CodId_Categoria_Fk As Nullable(Of Integer)
    Public Property Premio As Nullable(Of Decimal)
    Public Property ImpSegurada As Nullable(Of Decimal)
    Public Property Argumentacao As Boolean
    Public Property Cancelamento As Boolean
    Public Property Retido As Boolean
    Public Property CodId_Motivo As Nullable(Of Integer)
    Public Property Canc_Local As Nullable(Of Integer)
    Public Property Canc_Data As Nullable(Of Integer)
    Public Property Canc_Codigo As Nullable(Of Integer)
    Public Property Canc_OK As Boolean
    Public Property Canc_Valor_Devolucao As Nullable(Of Decimal)
    Public Property Canc_Ok_Data As Nullable(Of Date)
    Public Property Canc_Nok As Boolean
    Public Property Canc_Nok_Data As Nullable(Of Date)
    Public Property Canc_Nok_Motivo As String
    Public Property Nivel2_Enviar As Boolean
    Public Property Nivel2_Enviado As Boolean
    Public Property Nivel2_Enviado_Data As Nullable(Of Date)
    Public Property Nivel2_Cancelado As Boolean
    Public Property Nivel2_Cancelado_Data As Nullable(Of Date)
    Public Property Login_Operador As String
    Public Property Canc_Enviar_Robo As Boolean
    Public Property Canc_Enviar_Robo_Data As Nullable(Of Date)
    Public Property Canc_Enviar_Robo_Login As String
    Public Property Canc_Processamento_Data As Nullable(Of Date)
    Public Property Canc_Valor_Alcada As Nullable(Of Decimal)
    Public Property Canc_Dias_Alcada As Nullable(Of Integer)
    Public Property Canc_Nok_Alcada As Boolean
    Public Property Alcada As Boolean
    Public Property Nivel2_Enviado_Login As String
    Public Property Nivel2_Cancelado_Login As String
    Public Property CM_Enviado As Boolean
    Public Property CM_Enviado_Data As Nullable(Of Date)
    Public Property CM_Enviado_Login As String
    Public Property CM_Calc_VC As Boolean
    Public Property CM_Enviar As Boolean
    Public Property ATM As Boolean
    Public Property SMS As Boolean
    Public Property N_Emitido As Boolean
    Public Property Qtde_Parcelas As Nullable(Of Integer)
    Public Property ClienteAgencia As Boolean
    Public Property MatriculaGerente As String
    Public Property CodId_Motivo2 As Nullable(Of Integer)
    Public Property Atrito_VendaNRec As Boolean
    Public Property Atrito_VendaNRec_Login As String
    Public Property Atrito_VendaNRec_Data As Nullable(Of Date)
    Public Property Atrito_CancNEfetuado As Boolean
    Public Property Atrito_CancNEfetuado_Login As String
    Public Property Atrito_CancNEfetuado_Data As Nullable(Of Date)
    Public Property CodId_Cargo_Fk As Nullable(Of Integer)
    Public Property Atrito_CodId_Procedente As Nullable(Of Integer)
    Public Property Oferta As Boolean
    Public Property Oferta_Proc_OK As Boolean
    Public Property Oferta_Proc_NOK As Boolean
    Public Property Oferta_Proc_NOK_Motivo As String
    Public Property Oferta_Proc_Data As Nullable(Of Date)
    Public Property Oferta_Produto_VC As Nullable(Of Integer)
    Public Property Oferta_Produto_Grupo As Nullable(Of Integer)
    Public Property Oferta_Cod_Ferrari As Nullable(Of Integer)
    Public Property Oferta_ImpSeg As Nullable(Of Decimal)
    Public Property Oferta_Premio As Nullable(Of Decimal)
    Public Property Endosso As Boolean
    Public Property Endosso_Proc_OK As Boolean
    Public Property Endosso_Proc_NOK As Boolean
    Public Property Endosso_Proc_NOK_Motivo As String
    Public Property Endosso_Proc_NOK_Obs As String
    Public Property Endosso_Proc_Data As Nullable(Of Date)
    Public Property Endosso_ImpSeg As Nullable(Of Decimal)
    Public Property Endosso_Premio As Nullable(Of Decimal)
    Public Property Endosso_Enviar_Robo As Boolean
    Public Property Endosso_Enviar_Robo_Data As Nullable(Of Date)
    Public Property Endosso_Enviar_Robo_Login As String
    Public Property Endosso_Proposta As Nullable(Of Long)
    Public Property Endosso_Liberado As Boolean
    Public Property Venda As Boolean
    Public Property Venda_Proc_OK As Boolean
    Public Property Venda_Proc_NOK As Boolean
    Public Property Venda_Proc_NOK_Motivo As String
    Public Property Venda_Proc_NOK_Obs As String
    Public Property Venda_Proc_Data As Nullable(Of Date)
    Public Property Venda_Produto_VC As Nullable(Of Integer)
    Public Property Venda_ImpSeg As Nullable(Of Decimal)
    Public Property Venda_Premio As Nullable(Of Decimal)
    Public Property Venda_Enviar_Robo As Boolean
    Public Property Venda_Enviar_Robo_Data As Nullable(Of Date)
    Public Property Venda_Enviar_Robo_Login As String
    Public Property Venda_Proposta As Nullable(Of Long)
    Public Property CCred_TFC As Boolean
    Public Property CCred_TFC_Bandeira As Nullable(Of Integer)
    Public Property CCred_TFC_Numero As Nullable(Of Integer)
    Public Property CCred_TFC_Proc_OK As Boolean
    Public Property CCred_TFC_Proc_NOK As Boolean
    Public Property CCred_TFC_Proc_NOK_Motivo As String
    Public Property CCred_TFC_Proc_Data As Nullable(Of Date)
    Public Property CCred_TFC_Enviar_Robo As Boolean
    Public Property CCred_TFC_Enviar_Robo_Data As Nullable(Of Date)
    Public Property CCred_TFC_Enviar_Robo_Login As String
    Public Property CCred_TFC_Proposta As Nullable(Of Long)
    Public Property CCred_TFC_Liberado As Boolean
    Public Property Logradouro As String
    Public Property Numero As String
    Public Property Complemento As String
    Public Property Bairro As String
    Public Property Cidade As String
    Public Property UF As String
    Public Property CEP As String
    Public Property Tipo_Imovel As Nullable(Of Integer)
    Public Property Obs As String
    Public Property Canc_Lote As Nullable(Of Integer)
    Public Property Canc_Lote_Dta As Nullable(Of Date)
    Public Property Canc_Lote_Login As String
    Public Property Canc_Lote_Proc_Ok As Boolean
    Public Property Canc_Lote_Processando As Boolean
    Public Property DataDebito As Nullable(Of Date)
    Public Property Nivel1_Enviar As Boolean
    Public Property Nivel1_Enviado As Boolean
    Public Property Nivel1_Enviado_Data As Nullable(Of Date)
    Public Property Nivel1_Emitido As Boolean
    Public Property Nivel2_Emitido_Data As Nullable(Of Date)
    Public Property Nivel1_Ok As Boolean
    Public Property Nivel1_Enviado_Login As String
    Public Property Nivel1_Cancelado_Login As String
    Public Property Nivel1_Obs As String
    Public Property Nivel1_Ok_Data As Nullable(Of Date)
    Public Property Nivel1_Ok_Login As String
    Public Property Nivel3_Enviado As Boolean
    Public Property Nivel3_Enviado_Data As Nullable(Of Date)
    Public Property Nivel3_Enviado_Login As String
    Public Property Nivel3_Ok As Boolean
    Public Property Nivel3_Ok_Data As Nullable(Of Date)
    Public Property Nivel3_Ok_Login As String
    Public Property Nivel2_Ok As Boolean
    Public Property Nivel2_Ok_Data As Nullable(Of Date)
    Public Property Nivel2_Ok_Login As String
    Public Property Nivel2_Emitido As Boolean
    Public Property Nivel2_Obs As String
    Public Property CCred_TFC_Proc_NOK_Obs As String
    Public Property Oferta_CodId_Plano As Nullable(Of Integer)
    Public Property Venda_CodId_Plano As Nullable(Of Integer)
    Public Property Venda_Liberado As Boolean
    Public Property Inibido As Boolean
    Public Property Inibido_Data As Nullable(Of Date)
    Public Property N_Inibido As Boolean
    Public Property N_Inibido_Data As Nullable(Of Date)
    Public Property PE As Boolean
    Public Property PE_Marcar As Boolean
    Public Property PE_ExportadoVC90 As Boolean
    Public Property PE_Exportado_Login As String
    Public Property PE_Exportado_Data As Nullable(Of Date)
    Public Property PE_VC90_OK As Boolean
    Public Property PE_VC90_OK_Login As String
    Public Property PE_VC90_OK_Data As Nullable(Of Date)
    Public Property PE_Status_Rector As String
    Public Property Oferta_Marcar As Boolean
    Public Property Oferta_Ferrari_Exp As Boolean
    Public Property Oferta_Ferrari_Exp_Data As Nullable(Of Date)
    Public Property Oferta_Ferrari_Exp_Login As String
    Public Property PE_VC As Boolean
    Public Property DDD2 As String
    Public Property Celular As String
    Public Property Canc_Nok_Obs As String
    Public Property Enviar As Boolean
    Public Property Canc_OK_Manual_Obs As String
    Public Property Canc_OK_Manual_Login As String
    Public Property N_Inibido_Encontrado As Boolean
    Public Property N_Inibido_N_Encontrado As Boolean
    Public Property N_Inibido_Encontrado_VCAL_Enviar As Boolean
    Public Property N_Inibido_Encontrado_VCAL As Boolean
    Public Property N_Inibido_Encontrado_VCAL_Data As Nullable(Of Date)
    Public Property N_Inibido_Encontrado_VCAL_Login As String
    Public Property NCorrentista_OP As Boolean
    Public Property NCorrentista_DOC As Boolean
    Public Property Protocolo_Off As Nullable(Of Long)
    Public Property ChEsp As Nullable(Of Boolean)
    Public Property ChEsp_Ok As Nullable(Of Boolean)
    Public Property ChEsp_Nok As Nullable(Of Boolean)
    Public Property ChEsp_Enviar_Robo As Nullable(Of Boolean)
    Public Property ChEsp_Enviar_Robo_Data As Nullable(Of Date)
    Public Property ChEsp_Enviar_Robo_Login As String
    Public Property ChEsp_Proc_Robo_Data As Nullable(Of Date)
    Public Property ChEsp_Proc_Robo_Login As String
    Public Property Num_Protocolo_SAC As Nullable(Of Long)
    Public Property Email As String
    Public Property Nivel3_Obs As String
    Public Property Nivel3_Enviado_Nivel2 As Boolean
    Public Property Nivel3_Enviado_Nivel2_Data As Nullable(Of Date)
    Public Property Nivel3_Enviado_Nivel2_Login As String
    Public Property Nivel2_SolFinal As Boolean
    Public Property Nivel2_SolFinal_Obs As String
    Public Property Nivel2_SolFinal_Login As String
    Public Property Nivel2_SolFinal_Data As Nullable(Of Date)
    Public Property Canc_Status_Rector As String
    Public Property Canc_Status_Rector_Data As Nullable(Of Date)
    Public Property Canc_Status_Rector_Ok As Boolean
    Public Property Canc_VC_OK As Nullable(Of Boolean)
    Public Property Canc_VC_OK_Devolucao As Nullable(Of Boolean)
    Public Property Connect_Exp As Boolean
    Public Property Connect_aExp As Boolean

End Class
