'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tbl_Retencao_Meta_PJ
    Public Property Mesref As Integer
    Public Property Meta_Open As Nullable(Of Double)
    Public Property Meta_Related As Nullable(Of Double)

End Class
