'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tbl_Canc_Codigo
    Public Property CodId_CCod_Pk As Integer
    Public Property CodId_CLocal_Fk As Nullable(Of Integer)
    Public Property Cod_Cancelamento As Nullable(Of Integer)
    Public Property Descricao As String

End Class
