'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tbl_Usuario
    Public Property Login As String
    Public Property NomeUsuario As String
    Public Property Site As Nullable(Of Integer)
    Public Property PerfilUsuario As Nullable(Of Integer)
    Public Property Supervisor As Nullable(Of Integer)
    Public Property Inativo As Boolean
    Public Property Perfil_Old As Nullable(Of Integer)
    Public Property CodId_Usuario As Integer

End Class
