'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tbl_ChEps_Situacoes_Robo
    Public Property Cod_Situacao As Integer
    Public Property Desc_Situacao As String
    Public Property Status_OK As Nullable(Of Boolean)

End Class
