'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tbl_Canc_Alcada
    Public Property CodId_Alcada_Pk As Integer
    Public Property CodId_Prod_Grupo_Fk As Nullable(Of Integer)
    Public Property Valor As Nullable(Of Decimal)
    Public Property Dias As Nullable(Of Integer)
    Public Property Data_Inicio As Nullable(Of Date)

End Class
