'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tbl_Plano
    Public Property CodId_Plano As Integer
    Public Property CodProduto As Nullable(Of Integer)
    Public Property Segmento As Nullable(Of Integer)
    Public Property Categoria As Nullable(Of Integer)
    Public Property Tipo_Res As Nullable(Of Integer)
    Public Property ImpSeg As Nullable(Of Decimal)
    Public Property Premio As Nullable(Of Decimal)
    Public Property Inativo As Boolean
    Public Property OfertaDif As Boolean
    Public Property Venda As Boolean

End Class
