'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tbl_Canc_Tipo
    Public Property CodId_CTipo_Pk As Integer
    Public Property Tipo_Cancelamento As String
    Public Property Obs As String

End Class
