'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tbl_AgCc_Valida
    Public Property CodId_Ag_PK As Integer
    Public Property Banco As Nullable(Of Integer)
    Public Property Agencia As Nullable(Of Integer)
    Public Property Conta As Nullable(Of Integer)
    Public Property Ativo As Nullable(Of Boolean)

End Class
