'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tbl_Desfecho
    Public Property CodId_Desfecho As Integer
    Public Property CodId_Prod_Grupo_Fk As Nullable(Of Integer)
    Public Property CodId_TipoRet_Fk As Nullable(Of Integer)
    Public Property CodId_CMotivo_Fk As Nullable(Of Integer)
    Public Property CodId_CLocal_Fk As Nullable(Of Integer)
    Public Property Cod_Cancelamento As Nullable(Of Integer)
    Public Property CodId_CData_Fk As Nullable(Of Integer)
    Public Property CodId_CTipo_Fk As Nullable(Of Integer)
    Public Property Inativo As Boolean
    Public Property Retido As Boolean
    Public Property Alcada As Boolean

End Class
