'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tbl_Produto
    Public Property CodProduto As Integer
    Public Property CodProduto_Rector As Nullable(Of Integer)
    Public Property Cod_GCA As Nullable(Of Integer)
    Public Property CodId_Grupo_Fk As Nullable(Of Integer)
    Public Property Apolice As Nullable(Of Integer)
    Public Property Ramo As Nullable(Of Integer)
    Public Property NomeProduto As String
    Public Property Segmento As Nullable(Of Boolean)
    Public Property TipoRetencao_Fk As Nullable(Of Integer)
    Public Property Inativo As Boolean
    Public Property Limite_Idade As Nullable(Of Integer)
    Public Property Classe As Nullable(Of Integer)
    Public Property Ch_Esp As Nullable(Of Boolean)
    Public Property Cia As Nullable(Of Integer)

End Class
