'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tbl_Canc_Motivo2
    Public Property CodId_CMotivo2_Pk As Integer
    Public Property CodId_CMotivo_Fk As Integer
    Public Property Motivo As String
    Public Property Retido As Boolean
    Public Property Inelegivel As Boolean
    Public Property CodId_GCA As Nullable(Of Integer)
    Public Property Inativo As Boolean

End Class
