'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tbl_PzCurto_Percentual_Calc
    Public Property Id_Percentual_Calc As Integer
    Public Property Percent_Prazo_Segurado As Nullable(Of Double)
    Public Property Percent_Premio_Retido As Nullable(Of Double)
    Public Property Percent_Premio_Devolucao As Nullable(Of Double)

End Class
