'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tbl_Dash_Template
    Public Property CodId_Dash As Integer
    Public Property Proc_Dash As String
    Public Property Body As String
    Public Property BodyVar_Loop As String
    Public Property BodyVarSet_Loop As String
    Public Property Body2 As String
    Public Property Body_Loop As String
    Public Property From_Where As String

End Class
