'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tsys_Parametro
    Public Property CodParametro As Integer
    Public Property NomeParametro As String
    Public Property ValorParametro As String
    Public Property TipoDados As Nullable(Of Integer)
    Public Property Descricao As String
    Public Property strBackup As String
    Public Property Permit As Nullable(Of Boolean)

End Class
